function [brightnessVal, contrastVal, sepiaVal, grayVal, negativeVal] = filter_settings()
    % Default values
    brightnessVal = 0;
    contrastVal = 1;
    sepiaVal = 0;
    grayVal = 0;
    negativeVal = 0;

    % Create settings window
    f = figure('Name', 'Batch Settings', 'NumberTitle', 'off', ...
               'Position', [200 200 500 400], ...
               'Color', [0.15 0.15 0.15], ...
               'MenuBar', 'none', ...
               'ToolBar', 'none', ...
               'Resize', 'off', ...
               'WindowStyle', 'modal');

    yPos = 0.75; 
    step = 0.15;

    % Sliders
    [hBrightnessSlider, hBrightnessValue] = makeSlider('Brightness', -100, 100, 0, yPos, [0.7 0.9 1]);
    yPos = yPos - step;

    [hContrastSlider, hContrastValue] = makeSlider('Contrast', 0.5, 2, 1, yPos, [1 0.7 0.9]);
    yPos = yPos - step;

    [hSepiaSlider, hSepiaValue] = makeSlider('Sepia', 0, 1, 0, yPos, [0.9 0.7 0.5]);
    yPos = yPos - step;

    [hGraySlider, hGrayValue] = makeSlider('Grayscale', 0, 1, 0, yPos, [0.7 0.9 1]);
    yPos = yPos - step;

    [hNegativeSlider, hNegativeValue] = makeSlider('Negative', 0, 1, 0, yPos, [1 0.6 0.6]);

    % Confirm button
    uicontrol('Style', 'pushbutton', 'String', '✅ Apply Settings', ...
              'Units', 'normalized', 'Position', [0.35 0.05 0.3 0.08], ...
              'FontSize', 12, 'FontWeight', 'bold', ...
              'BackgroundColor', [0.2 0.7 0.2], ...
              'ForegroundColor', [1 1 1], ...
              'Callback', @(~,~) applySettings());

    uiwait(f);

    % --- Nested functions ---
    function [hSlider, hValue] = makeSlider(name, minVal, maxVal, initVal, y, color)
    uicontrol('Style', 'text', 'String', name, ...
              'Units', 'normalized', 'Position', [0.1 y 0.2 0.08], ...
              'FontSize', 11, 'FontWeight', 'bold', ...
              'BackgroundColor', [0.15 0.15 0.15], ...
              'ForegroundColor', color, ...
              'HorizontalAlignment', 'left');

    % Create value label first
    hValue = uicontrol('Style', 'text', 'String', num2str(initVal), ...
                       'Units', 'normalized', 'Position', [0.8 y 0.1 0.08], ...
                       'FontSize', 10, ...
                       'BackgroundColor', [0.2 0.2 0.2], ...
                       'ForegroundColor', [0.95 0.95 0.95], ...
                       'HorizontalAlignment', 'center');

    % Then create slider and link it to hValue
    hSlider = uicontrol('Style', 'slider', 'Min', minVal, 'Max', maxVal, ...
                        'Value', initVal, 'Units', 'normalized', ...
                        'Position', [0.3 y 0.45 0.08], ...
                        'BackgroundColor', [0.25 0.25 0.25], ...
                        'SliderStep', [0.01 0.1], ...
                        'Callback', @(src,~) set(hValue, 'String', ...
                                          sprintf('%.2f', get(src,'Value'))));
    end


    function applySettings()
        brightnessVal = get(hBrightnessSlider, 'Value');
        contrastVal   = get(hContrastSlider, 'Value');
        sepiaVal      = get(hSepiaSlider, 'Value');
        grayVal       = get(hGraySlider, 'Value');
        negativeVal   = get(hNegativeSlider, 'Value');
        uiresume(f);
        delete(f);
    end
end
